/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import org.hibernate.Session;
import dao.DAO;
import model.Produto;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import oracle.jrockit.jfr.JFR;

public class JFrmCadProduto extends javax.swing.JFrame {
    private Produto p;
    private Session sessao;
    private List <Produto> lista;
    private DefaultTableModel dtm;
    /**
     * Creates new form JFrmCadProduto
     */
    public JFrmCadProduto() {
        initComponents();
        
        sessao = DAO.getSessionFactory().openSession();
        lista = new ArrayList<Produto>();
        dtm = (DefaultTableModel)tblProduto.getModel();
        
        popularTabela();
        
    }
    
     private void atualizarTabela(){
        int aux = lista.size() - 1;
        Produto p = lista.get(aux);
       
        dtm.addRow(p.toLinha());
    }
     
     private void popularTabela(){
       int aux;
       
       lista = sessao.createQuery("from Produto").list();
       
       if(lista.size() > 0){
                   
           
           for(aux = 0; aux<lista.size(); aux++){
               
               Produto p = lista.get(aux);
     
               dtm.addRow(p.toLinha());
           }
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        spnPreco = new javax.swing.JSpinner();
        spnMargem = new javax.swing.JSpinner();
        spnEstoque = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marca", "Preço de compra", "Margem de lucro", "Estoque", "Preço de venda", "Preço de estoque"
            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        jLabel1.setText("Nome");

        jLabel2.setText("Preço de compra");

        jLabel3.setText("Marca");

        jLabel4.setText("Margem de lucro");

        jLabel5.setText("Estoque");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        spnPreco.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));

        spnMargem.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));

        spnEstoque.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton2.setText("Alteração");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNome)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnMargem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnMargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnExcluir)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(960, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sessao.getSessionFactory().close();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        p = new Produto(txtNome.getText(), 
                        txtMarca.getText(), 
                        (float)spnPreco.getValue(), 
                        (float)spnMargem.getValue(), 
                        (int)spnEstoque.getValue());
                       
        try{
           sessao.beginTransaction();
           sessao.save(p);
           sessao.getTransaction().commit();
           lista.add(p);
           
           atualizarTabela();
           
       }catch(Exception ex){
           ex.printStackTrace();
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
     
        int i = tblProduto.getSelectedRow();
        
        if(tblProduto.getSelectedRow() != -1){
  
        DefaultTableModel dtmProdutos = (DefaultTableModel) tblProduto.getModel();
        dtmProdutos.removeRow(tblProduto.getSelectedRow());    

                    Produto p = lista.get(i);
                           
                    try{
                        sessao.beginTransaction();
                        sessao.delete(p);
                        sessao.getTransaction().commit();
                        lista.remove(p); 
                        
                    }catch(Exception ex){
                        ex.printStackTrace();
                    }
                
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!!!");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       int lin = tblProduto.getSelectedRow();
       if(tblProduto.getSelectedRow() != -1){  
           
            tblProduto.setValueAt(txtNome.getText() ,tblProduto.getSelectedRow(), 1);
            tblProduto.setValueAt(txtMarca.getText() ,tblProduto.getSelectedRow(), 2);
            tblProduto.setValueAt(spnEstoque.getValue() ,tblProduto.getSelectedRow(), 3);  
            tblProduto.setValueAt(spnMargem.getValue() ,tblProduto.getSelectedRow(), 4);  
            tblProduto.setValueAt(spnEstoque.getValue() ,tblProduto.getSelectedRow(), 5);  
            Produto p = lista.get(lin);
            
            lista.add(lin, p);
            
            
             try{
                        sessao.beginTransaction();
                        sessao.update(p);
                        sessao.getTransaction().commit();
   
                    }catch(Exception ex){
                        ex.printStackTrace();
                    }
            
        }else{
           JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!!!");
       } 
       
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        
         if(tblProduto.getSelectedRow() != -1){
             
             txtNome.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 1).toString());
             txtMarca.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2).toString());
             spnPreco.setValue(tblProduto.getValueAt(tblProduto.getSelectedRow(), 3));
             spnMargem.setValue(tblProduto.getValueAt(tblProduto.getSelectedRow(), 4));
             spnEstoque.setValue(tblProduto.getValueAt(tblProduto.getSelectedRow(), 5));
             
         }else{
           JOptionPane.showMessageDialog(null, "Selecione um produto para excluir!!!");
       }
        
    }//GEN-LAST:event_tblProdutoMouseClicked

    public void excluir(){
        
        int lin = tblProduto.getSelectedRow();
        
        if(lin >= 0){
            
            
            Produto p = new Produto("", "", 0, 0, 0);
            
            System.out.println(p.getId()+ p.getNome());
            
            if(JOptionPane.showConfirmDialog(JFrmCadProduto.this, "Deseja realmente excluir o produto"+p.getNome()+"?",
                                            "Confirma a exclusão", JOptionPane.YES_NO_OPTION)==0){
 
                sessao.beginTransaction();
                sessao.delete(p);
                sessao.getTransaction().commit();
                
                JOptionPane.showMessageDialog(JFrmCadProduto.this, "Produto excluído com sucesso");
                
                dtm.removeRow(lin);
                lista.remove(lin);
            }
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmCadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnEstoque;
    private javax.swing.JSpinner spnMargem;
    private javax.swing.JSpinner spnPreco;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
